[package]
name = "svg_guardian"
version = "0.0.2"
edition = "2021"
authors = ["Alex Beznos <alex@yuma.ai>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6" }
svg-hush = { version = "0.9.4" }
